[package]
name = "hnsw2"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[dependencies]
num = "0.4.3"
fixedbitset = "0.5.7"
serde = { version = "1.0", features = ["derive"] }
rand = "0.9"
rayon = "1.5.1"
bincode = "1.3.3"

[features]
simd = []
no_thread = []